testing workflow

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -116,37 +116,15 @@ jobs:
         insecure_skip_tls_verify: true
         namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-#    - name: Deploy and Apply Kompose Files
-#      run: |
-#        oc apply -f api-deploymentconfig.yaml
-#        oc apply -f api-imagestream.yaml
-#        oc apply -f api-service.yaml
-#        oc apply -f env-configmap.yaml
-#        oc apply -f mysql-db-deploymentconfig.yaml
-#        oc apply -f mysql-db-imagestream.yaml
-#        oc apply -f mysql-db-service.yaml
-#
-#    - name: Print application URL
-#      env:
-#        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-#        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-#      run: |
-#        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-#        echo
-#        echo "======================== Your application is available at: ========================"
-#        echo ${{ env.ROUTE }}
-#        echo "==================================================================================="
-#        echo
-#        echo "Your app can be taken down with: 'oc delete all --selector='${{ env.SELECTOR }}''"
-
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ steps.push-image.outputs.registry-path }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
+    - name: Deploy and Apply Kompose Files
+      run: |
+        oc apply -f api-deploymentconfig.yaml
+        oc apply -f api-imagestream.yaml
+        oc apply -f api-service.yaml
+        oc apply -f env-configmap.yaml
+        oc apply -f mysql-db-deploymentconfig.yaml
+        oc apply -f mysql-db-imagestream.yaml
+        oc apply -f mysql-db-service.yaml
 
     - name: Print application URL
       env:
@@ -159,4 +137,26 @@ jobs:
         echo ${{ env.ROUTE }}
         echo "==================================================================================="
         echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+        echo "Your app can be taken down with: 'oc delete all --selector='${{ env.SELECTOR }}''"
+
+#    - name: Create and expose app
+#      id: deploy-and-expose
+#      uses: redhat-actions/oc-new-app@v1
+#      with:
+#        app_name: ${{ env.APP_NAME }}
+#        image: ${{ steps.push-image.outputs.registry-path }}
+#        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+#        port: ${{ env.APP_PORT }}
+#
+#    - name: Print application URL
+#      env:
+#        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+#        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+#      run: |
+#        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+#        echo
+#        echo "======================== Your application is available at: ========================"
+#        echo ${{ env.ROUTE }}
+#        echo "==================================================================================="
+#        echo
+#        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
